### ISSUE TITLE
Problem with another package

### ISSUE THREAD

**Issue by felocru** [noxify/gridsome-plugin-remote-image#18]
I recently added this package:
gridsome-plugin-flexsearch
By configuring the package in gridsome.config.js
I present this problem several times:
```
(node:6042) UnhandledPromiseRejectionWarning: Error: Could not find node to update with id: 17
    at Collection.updateNode (/.../node_modules/gridsome/lib/store/Collection.js:124:13)
    at /.../node_modules/@noxify/gridsome-plugin-remote-image/gridsome.server.js:133:28
(node:6042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 102)
```

What could be happening? Thank you.

**Comment by noxify** [comment]
Related:
* https://github.com/gridsome/gridsome/issues/1223
* https://github.com/thetre97/gridsome-plugin-flexsearch/issues/61
